# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ornek(object):
    def setupUi(self, ornek):
        ornek.setObjectName("ornek")
        ornek.resize(509, 371)
        self.liste = QtWidgets.QListWidget(ornek)
        self.liste.setGeometry(QtCore.QRect(10, 10, 481, 241))
        self.liste.setObjectName("liste")
        self.btn_ekle = QtWidgets.QPushButton(ornek)
        self.btn_ekle.setGeometry(QtCore.QRect(410, 320, 80, 25))
        self.btn_ekle.setObjectName("btn_ekle")
        self.edit_eleman = QtWidgets.QLineEdit(ornek)
        self.edit_eleman.setGeometry(QtCore.QRect(130, 320, 251, 25))
        self.edit_eleman.setObjectName("edit_eleman")
        self.btn_sil = QtWidgets.QPushButton(ornek)
        self.btn_sil.setGeometry(QtCore.QRect(20, 320, 80, 25))
        self.btn_sil.setObjectName("btn_sil")

        self.retranslateUi(ornek)
        self.btn_sil.clicked.connect(ornek.btn_sil_basildi) # type: ignore
        self.btn_ekle.clicked.connect(ornek.btn_ekle_basildi) # type: ignore
        self.liste.itemActivated['QListWidgetItem*'].connect(ornek.list_eleman_tiklandi) # type: ignore
        self.liste.clicked['QModelIndex'].connect(ornek.list_eleman_tiklandi) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ornek)

    def retranslateUi(self, ornek):
        _translate = QtCore.QCoreApplication.translate
        ornek.setWindowTitle(_translate("ornek", "Dialog"))
        self.btn_ekle.setText(_translate("ornek", "Ekle"))
        self.btn_sil.setText(_translate("ornek", "Sil"))
